### ISSUE TITLE
1.0.0.rc.1 throws stacktrace on rebuild or preview

### ISSUE THREAD

**Issue by stefri** [bpm/bpm#46] opened 2011-09-09 16:53 UTC
Just upgraded to 1.0.0.rc.1 and now I get this stacktrace when running "bpm rebuild":

```
Fetching packages from remote...
Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `block in satisfied_by?': undefined method `call' for nil:NilClass (NoMethodError)
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `each'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `all?'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `satisfied_by?'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:325:in `block in search'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `select'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `search'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:280:in `find_name'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:214:in `installation_satisfies_dependency?'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:204:in `ensure_dependency'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:418:in `block in ensure_dependencies_met'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `each'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `ensure_dependencies_met'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:136:in `install'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:96:in `block (2 levels) in install'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:66:in `each'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:66:in `block in install'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems.rb:221:in `with_rubygems_compat'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:54:in `install'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/remote.rb:83:in `block in install'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/libgems.rb:43:in `with_silence'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/remote.rb:81:in `install'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:621:in `core_fetch_dependency'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:600:in `block in core_fetch_dependencies'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:599:in `each'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:599:in `core_fetch_dependencies'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:278:in `fetch_dependencies'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:179:in `verify_and_repair'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:286:in `build'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/cli/base.rb:141:in `rebuild'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/lib/bpm/cli/base.rb:25:in `start'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.1/bin/bpm:8:in `<top (required)>'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in `load'
    from /Users/steffen/.rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in `<main>'
```

**Comment by stefri** [comment] 2011-09-09 17:16
Sorry, I got it. Used ">= 0.pre" as sproutcore version in my package file which does not work anymore. However, would be nice if the error message for wrong version numbers would be slightly more self-speaking.

**Comment by stefri** [comment] 2011-09-12 15:59
This error isn't caused by the prerelease version, instead I had to upgrade my installed ruby version to 1.9.2-p290. Otherwise this happens again when cleaning the local bpm package cache.

**Comment by florish** [comment] 2011-09-12 18:54
stefri: Had the same problem. After upgrading to ruby 1.9.2-p290, the hello_world [wiki instructions](https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0) only work if I remove the "--pre" from "bpm add sproutcore --pre". I was about to edit the wiki page, but saw you already did that and reverted your changes... so it works for you with "--pre" still set? I use bpm 1.0.0.rc by the way.

**Comment by stefri** [comment] 2011-09-12 18:57
florish: Do you still encounter this issue even with ruby 1.9.2-p290? Because as soon as I upgraded to -p290 this problem was gone. If you still have those problems maybe I should reopen this issue ...

**Comment by florish** [comment] 2011-09-12 19:16
I had some problems with ruby/rvm upgrades, but checked everything and reinstalled bpm 1.0.0.rc1 gem in -p290. Did `bpm init hello_world`, `cd hello_world` and then this:

```
(..)/hello_world $ bpm add sproutcore --pre
Fetching packages from remote...
Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `block in satisfied_by?': undefined method `call' for nil:NilClass (NoMethodError)
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `each'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `all?'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `satisfied_by?'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:325:in `block in search'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `select'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `search'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:280:in `find_name'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:214:in `installation_satisfies_dependency?'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:204:in `ensure_dependency'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:418:in `block in ensure_dependencies_met'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `each'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `ensure_dependencies_met'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:136:in `install'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:96:in `block (2 levels) in install'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:66:in `each'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:66:in `block in install'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems.rb:221:in `with_rubygems_compat'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/dependency_installer.rb:54:in `install'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/remote.rb:83:in `block in install'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/libgems_ext/libgems.rb:43:in `with_silence'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/remote.rb:81:in `install'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:621:in `core_fetch_dependency'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:600:in `block in core_fetch_dependencies'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:599:in `each'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:599:in `core_fetch_dependencies'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/project.rb:217:in `add_dependencies'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/cli/base.rb:105:in `add'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/lib/bpm/cli/base.rb:25:in `start'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.1/bin/bpm:8:in `<top (required)>'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `load'
    from /Users/floris/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `<main>'
```

So the problem is still there for me... 

Without the --pre, sproutcore does get installed, but running `bpm preview` gives me a "exports is not defined" JS error in Firebug, something similar to [this topic](https://groups.google.com/d/topic/sproutcore/TSwOf6R4yUU/discussion). But that's a different kind of error, won't get into the details here.

**Comment by stefri** [comment] 2011-09-12 19:18
Reopened because I'm not quite sure how to really solve this issue ...

**Comment by wagenet** [comment] 2011-09-14 09:43
I think the exports issue is fixed in master now. I'll release RC2 shortly.

**Closed as completed by wagenet** 2011-09-14 09:43 UTC
Labels: bug

**Comment by florish** [comment] 2011-09-14 14:22
wagenet: can confirm rc2 works, thanks! Both the ruby error on `bpm add sproutcore --pre` and the exports issue in JS are gone.
