### ISSUE TITLE
Circular dependency error when using require

### ISSUE THREAD

**Issue by charlesjolley** [bpm/bpm#5] opened 2011-08-05 05:17 UTC
I have seen this same error in JS files as well so it's not just CSS, but you can easily reproduce the error by cloning:

https://github.com/charlesjolley/WebIntents-Examples

Then try to run `bpm rebuild`:

Building static assets...
~ Using fetched package 'WebIntents' (0.1.0)
~ Building bpm_libs.js... (gzipped size: 8 Kb)
~ Building bpm_styles.css.../Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:150:in `check_circular_dependency!': /Users/charles/Source/bpm/ports/WebIntents-Examples/css/reset.css has already been required (Sprockets::CircularDependencyError)
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:173:in`build_dependencies_paths_and_assets'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:81:in `to_a'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:191:in`block in build_dependencies_paths_and_assets'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:185:in `each'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:185:in`build_dependencies_paths_and_assets'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:81:in `to_a'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:230:in`block in build_source'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/caching.rb:23:in `cache_hash'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:226:in`build_source'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/pipeline/generated_asset.rb:76:in `build_source'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/sprockets-2.0.0.beta.12/lib/sprockets/bundled_asset.rb:93:in`to_s'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/project.rb:277:in `block (2 levels) in build'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/project.rb:277:in`open'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/project.rb:277:in `block in build'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/project.rb:267:in`each'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/project.rb:267:in `build'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/lib/bpm/cli/base.rb:137:in`rebuild'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.beta.12/bin/bpm:7:in `<top (required)>'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in`load'
    from /Users/charles/.rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in `<main>'

**Comment by wagenet** [comment] 2011-08-16 22:03
This is caused by the require directive in your base.css. It seems that BPM has already required reset.css so we're now getting a duplicate call. If I remove this line it rebuild successfully.

**Comment by wagenet** [comment] 2011-08-30 22:55
I've verified this. This problem is that bpm_styles.css is already set up to load everything in the css directory. Which means that both base.css and reset.css are already in the queue. When it hits base.css it adds reset.css to the queue again and bam, circular require. I think the best way to deal with this to allow specifying only a file. In this case you'd say bpm_styles.css is based on base.css (instead of the entire directory). Then base.css would load up reset.css. Make sense? I hope so, because I'm closing this :)

**Closed as completed by wagenet** 2011-08-30 22:55 UTC
Labels: bug

**Comment by charlesjolley** [comment] 2011-08-30 23:10
So just to make sure I understand - in the bpm_styles.css I should say 'directories': ['base.css'], and then in base.css I require reset.css, which causes all of them to be included.  

Would another option be for me to just do:  'directories': ['base.css', 'reset.css'] which will cause them to be included in the proper order [and therefore I would NOT include the require command in the CSS files?

If this is the case, I think that would be a better recommendation (i.e. specify the files you want included in the proper order) than telling people to include a single file and then lean on requires.  Maybe we should change the 'directories' directive in bpm:build to 'files' instead?

**Comment by wagenet** [comment] 2011-08-30 23:12
Well you can't do that yet, but when we add support, it should be `files: ['base.css']` then require reset.css.
Like you said, you could do `files: ['reset.css', 'base.css']` (not what you typed but what I think you meant).
Of course, the only reason I can see to do it this way is if order matters.
